import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import JimiQuiz from '../components/JimiQuiz/JimiQuiz'
import Quiz from '../components/Quiz/Quiz'
import styles from '../styles/Home.module.css'

import questions from "../data/questions.json";

const Home: NextPage = () => {
  /*let questions = [
    { 
      question: "Hur många invånare har Finland?", 
      answers: [
        {answer: "5 miljoner", correct: false},
        {answer: "5.5 miljoner", correct: true},
        {answer: "6 miljoner", correct: false}
      ] 
    },
    { 
      question: "Hur många invånare har Sverige?", 
      answers: [
        {answer: "8 miljoner", correct: false}, 
        {answer: "9 miljoner", correct: false}, 
        {answer: "10 miljoner", correct: true},
        {answer: "11 miljoner", correct: false}
      ] 
    },
    { 
      question: "Använder javascript en compiler eller interpreter?", 
      answers: [
        {answer: "Interpreter", correct: true}, 
        {answer: "Compiler", correct: false}
      ] 
    },
  ];*/

  console.log(questions);
  

  return (
    <div className="flex justify-center items-center min-h-screen">
      <Head>
        <title>Components Website</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <JimiQuiz 
      title='My Quiz' 
      description='Det är en random quiz gjort av en idiot vid namn Willi'
      startButtonText="Start"
      questions={questions}/>
    </div>
  )
}

export default Home
