import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import crypto from "crypto";
import { useState } from 'react';
import HashGenerator from '../components/HashGenerator/HashGenerator';
import PasswordGenerator from '../components/PasswordGenerator/PasswordGenerator';

const Home: NextPage = () => {
  const [txtText, setTxtText] = useState("");
  const [txtEncrypted, setTxtEncrypted] = useState("");
  console.log(txtText);

  const encrypt = () => {
    setTxtEncrypted(crypto.createHash("md5").update(txtText).digest("hex"));
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Hash Generator</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <PasswordGenerator />
      <HashGenerator />
      

    </div>
  )
}

export default Home
